PACKAGE_NAME="rtl8851bu"
PACKAGE_VERSION="1.19.10-78"
BUILT_MODULE_NAME[0]="8851bu"
MAKE="kernelver=$kernelver ./dkms-make.sh"
CLEAN="'make' clean"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
